import {
  AlarmClock, AlertOctagon, AlertTriangle, Award, Badge, BadgeAlert, BadgePlus, Ban, BookOpen,
  Cable, CalendarCheck, CalendarPlus, Camera, CheckCheck, Circle, Clapperboard,
  Clock, CloudOff, Cookie, Cpu, Crosshair, Crown, DoorOpen, DownloadCloud, Film,
  Dumbbell, Flag, Flame, FlaskConical, Frown, Gauge, Ghost, GitBranch, GraduationCap, HandHeart,
  HandHelping, Handshake, HeartHandshake, IdCard, ImageOff, Keyboard, Layers, Map,
  MapPinOff, Medal, MessageCircle, MessageSquare, MessageSquareWarning,
  MessagesSquare, MonitorX, Moon, Network, Radio, RadioTower, Rocket, RotateCcw, Server,
  Shield, Snail, Sparkles, Star, Sun, Swords, ThermometerSnowflake, Timer,
  TrendingUp, Trophy, Tv, UserCheck, UserPlus, UserRoundX, Users, UsersRound, UserX, Video,
  VolumeX, Wrench, XCircle, XOctagon, Zap, ZapOff,
} from "lucide-react";

const ICONS = {
  "alarm-clock": AlarmClock,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  award: Award,
  badge: Badge,
  "badge-alert": BadgeAlert,
  "badge-plus": BadgePlus,
  ban: Ban,
  "book-open": BookOpen,
  cable: Cable,
  "calendar-check": CalendarCheck,
  "calendar-plus": CalendarPlus,
  camera: Camera,
  "check-check": CheckCheck,
  circle: Circle,
  clapperboard: Clapperboard,
  clock: Clock,
  "cloud-off": CloudOff,
  cookie: Cookie,
  cpu: Cpu,
  crosshair: Crosshair,
  crown: Crown,
  "door-open": DoorOpen,
  "download-cloud": DownloadCloud,
  dumbbell: Dumbbell,
  film: Film,
  flag: Flag,
  flame: Flame,
  flask: FlaskConical,
  frown: Frown,
  gauge: Gauge,
  ghost: Ghost,
  "git-branch": GitBranch,
  "graduation-cap": GraduationCap,
  "hand-heart": HandHeart,
  "hand-helping": HandHelping,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "id-card": IdCard,
  "image-off": ImageOff,
  keyboard: Keyboard,
  layers: Layers,
  map: Map,
  "map-off": MapPinOff,
  medal: Medal,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-warning": MessageSquareWarning,
  "messages-square": MessagesSquare,
  "monitor-x": MonitorX,
  moon: Moon,
  network: Network,
  radio: Radio,
  broadcast: RadioTower,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  server: Server,
  shield: Shield,
  snail: Snail,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  swords: Swords,
  "thermometer-snowflake": ThermometerSnowflake,
  timer: Timer,
  "trending-up": TrendingUp,
  trophy: Trophy,
  tv: Tv,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  users: Users,
  "users-round": UsersRound,
  "users-x": UserRoundX,
  "user-x": UserX,
  video: Video,
  "volume-x": VolumeX,
  wrench: Wrench,
  "x-circle": XCircle,
  "x-octagon": XOctagon,
  zap: Zap,
  "zap-off": ZapOff,
};

export const ACHIEVEMENT_ICON_NAMES = Object.freeze(Object.keys(ICONS));

function normalizeIconName(value) {
  return String(value || "")
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

export function AchievementIcon({ name, fallback = "circle", ...props }) {
  const Icon = ICONS[normalizeIconName(name)] || ICONS[normalizeIconName(fallback)] || Circle;
  return <Icon {...props} />;
}
